jobs:
  workflow:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Pull Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./action/test

name: Action

on:
  schedule:
    - cron: "40 1/3 * * *"
